language: go
sudo: required
services:
  - docker
matrix:
  include:
  - go: 1.13.x
  - go: 1.14.x
    env: DEPLOY=true
  - go: tip
  allow_failures:
  - go: tip
script:
- CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static" -s' -o containerflight
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...
- ./system-tests/run.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true # Important, otherwise the build output would be purged.
  api_key:
    secure: aFH7PF6wBmmz3ZsjKiXIqPqYRhdv/Dj8UVrMVbmgJJzpsdxH+wmPXc+d5ZC83qHxMTQfeNwKhSGipED5Sa+xyvV5jA43+orvcyhq3LMy7/PM0FxdKuwMBvsUePqSDXnDroTLMjh2jRDiAzMJvalN6ffh3edNXPMef7QLaZ+zftEfCvSOXWyfXOz0w8YsyvMe4NcJWmSbf1ku2ewogibCJCRYyMfwTSufusCa3gMqU2tJF5gNNIDSCai3+JfC9CM8pPqhW6vZhoP8plKrzZOGZ2q5+Z9kFMbQovV7UApBYx+cJDE33BYR4BgzttkMkbfdJuxkAnlOH6R6oAl0Azh+HH/WEJiEChy0yfvtkv5Ldg9LOVbEdDiBTpQXqXj/+MCts2qf8/IGZbn7w4pThIOuX8BPZ1kthtfYEBXfM3uz29clb8SLxDeWiO++3i2L5feICGWv2yS4ZiTSEa63F2aLxKpkO+ceF2rcKPaE0B7FEahVrenYoa0vwLHQvC3Xsgh3S6nNdm5p1YdJ4SoOuHM0+aWetHRbZMv+W4ReWQlpE3bM2ax94BXQyoGTm+qL3IClgw55sJgeN711GCUCno62RkE+5Rs87h0R9iHSLILyRH29w51yhlQzPcK/nMZ2vcFTLzFPF6nbLEOd9rVpexFdZOdfsYWfBcPKYDIMd49eFkI=
  file:
    - containerflight_linux_amd64
    - containerflight_windows_amd64
    - containerflight_darwin_amd64
  script:
    - CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -s' -o containerflight_linux_amd64
    - CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -a -ldflags '-extldflags "-static" -s' -o containerflight_windows_amd64
    - CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -a -o containerflight_darwin_amd64
  on:
    repo: tjeske/containerflight
    tags: true # The deployment happens only if the commit has a tag.
    condition: $DEPLOY = true
    branch: master
